#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { compileLesson, validateLesson } = require("../core/lesson-spec.js");

const root = path.resolve(__dirname, "..");
const authoringRoot = path.join(root, "authoring");
const productionRoot = path.join(authoringRoot, "lessons");
const examplesRoot = path.join(authoringRoot, "examples");
const outputFile = path.join(root, "practice", "generated", "carry-lessons.js");
const catalog = JSON.parse(fs.readFileSync(path.join(authoringRoot, "catalogs", "carry-v1.json"), "utf8"));

function lessonFiles(directory) {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) return lessonFiles(fullPath);
    return entry.isFile() && entry.name.endsWith(".carry.json") ? [fullPath] : [];
  }).sort();
}

function readLesson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch (error) {
    throw new Error(`${path.relative(root, file)}: ${error.message}`);
  }
}

function validateFile(file) {
  const lesson = readLesson(file);
  const result = validateLesson(lesson, { catalog });
  if (!result.valid) {
    throw new Error(`${path.relative(root, file)}:\n- ${result.issues.join("\n- ")}`);
  }
  return lesson;
}

function browserModule(compiled) {
  const payload = JSON.stringify(compiled, null, 2);
  return `// Generated by scripts/compile-lessons.js. Edit authoring/lessons, not this file.\n(function registerCarryLessonSpecifications() {\n  window.CarryPractice = window.CarryPractice || { sections: {}, modes: {} };\n  const compiled = ${payload};\n  for (const entry of compiled) {\n    if (entry.target.kind === "long-operation") {\n      window.CarryPractice.modes.longOperations = window.CarryPractice.modes.longOperations || {};\n      window.CarryPractice.modes.longOperations[entry.target.key] = entry.workspace;\n      continue;\n    }\n    const section = window.CarryPractice.sections[entry.target.section] = window.CarryPractice.sections[entry.target.section] || {};\n    section[entry.workspace.id] = entry.workspace;\n  }\n})();\n`;
}

function compileAll() {
  const productionFiles = lessonFiles(productionRoot);
  const exampleFiles = lessonFiles(examplesRoot);
  if (!productionFiles.length) throw new Error("No production CLS lessons found.");
  [...productionFiles, ...exampleFiles].forEach(validateFile);
  return productionFiles.map((file) => compileLesson(readLesson(file), {
    catalog,
    source: path.relative(root, file)
  }));
}

function main() {
  const output = browserModule(compileAll());
  if (process.argv.includes("--check")) {
    if (!fs.existsSync(outputFile) || fs.readFileSync(outputFile, "utf8") !== output) {
      console.error("Compiled CLS output is stale. Run npm run lessons:compile.");
      process.exitCode = 1;
      return;
    }
    console.log("CLS validation passed and generated output is current.");
    return;
  }
  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(outputFile, output);
  console.log(`Compiled ${lessonFiles(productionRoot).length} CLS lesson to ${path.relative(root, outputFile)}.`);
}

try {
  main();
} catch (error) {
  console.error(error.message);
  process.exitCode = 1;
}
